### ISSUE TITLE
Add Browserstack automated JS tests

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-react-bootstrap#48]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-react-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-react-bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

the code could be something like this:

```yml
name: BrowserStack

on:
  push:
  workflow_dispatch:

env:
  FORCE_COLOR: 2
  NODE: 16

jobs:
  browserstack:
    runs-on: ubuntu-latest
    if: github.repository == 'trimble-oss/modus-react-bootstrap' && (!contains(github.event.commits[0].message, '[ci skip]') && !contains(github.event.commits[0].message, '[skip ci]'))
    timeout-minutes: 30

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.NODE }}"
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Run BrowserStack tests
        run: npm run js-test-cloud
        env:
          BROWSER_STACK_ACCESS_KEY: "${{ secrets.BROWSER_STACK_ACCESS_KEY }}"
          BROWSER_STACK_USERNAME: "${{ secrets.BROWSER_STACK_USERNAME }}"
          GITHUB_SHA: "${{ github.sha }}"
```

quick example above, the exact commands maybe different and JS tests need to be added first.

### Motivation and context

to help test and find JS bugs
