### ISSUE TITLE
Add Super Linter GitHub Action

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-react-bootstrap#77]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-react-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-react-bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

I know we already have a lot of linting and testing things - but I think it could be a good idea to add this GitHub Action too:
https://github.com/github/super-linter

### Motivation and context

The reason being is that it can catch bugs/issues with some things [you might not think about such as YML, XML, JSON formatting issues and many others](https://github.com/github/super-linter#supported-linters). We can set it to disable (not run) on things we test elsewhere (e.g. CSS and JS).

It's free to use and by GitHub - I use it on all my open source projects and find it really useful. It even checks GitHub Actions workflows for issues!

```yml
name: Lint Code Base

on:
  push:
    branches: [main]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JAVASCRIPT_DEFAULT_STYLE: prettier
          LINTER_RULES_PATH: /
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_EDITORCONFIG: false
          VALIDATE_MARKDOWN: false
```
